import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BgWrapper from "../components/Background/BgWrapper";
import { Providers } from "@/components/WalletConnect/Providers";
import HydrationZustandWrapper from "@/components/HydrationZustandWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
          <BgWrapper>
            <HydrationZustandWrapper>
              {children}
            </HydrationZustandWrapper>
          </BgWrapper>
        </Providers>
      </body>
    </html>
  );
}
